terraform {
  backend "s3" {
    # Same state bucket as the main stack, different key. `bucket` is supplied
    # via -backend-config=backend.hcl (the file generated by
    # scripts/bootstrap-state-bucket.sh works here too).
    key          = "eks-on-private-vpc/bootstrap.tfstate"
    region       = "eu-west-1"
    encrypt      = true
    use_lockfile = true
  }
}
