terraform {
  backend "s3" {
    # `bucket` is supplied via -backend-config=backend.hcl (generated by
    # scripts/bootstrap-state-bucket.sh) so the same code works across
    # accounts without editing this file.
    key          = "eks-on-private-vpc/terraform.tfstate"
    region       = "eu-west-1"
    encrypt      = true
    use_lockfile = true # Terraform >= 1.10 — native S3 lock, no DynamoDB
  }
}
